"""add is_pinned to proxy

Revision ID: d8693aa78c9e
Revises: 637504466573
Create Date: 2026-03-31 11:45:54.986378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8693aa78c9e'
down_revision: Union[str, Sequence[str], None] = '637504466573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'is_pinned')
    # ### end Alembic commands ###
